apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: shobhittestregistry.azurecr.io/task:latest
        ports:
        - containerPort: 8080
        resources:
         limits:
           cpu: 500m
         requests:
           cpu: 200m
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
        - name: MONGO_HOST
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: db_name
