apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbnVzZXJuYW1l
  mongo-root-password: bW9uZ29hZG1pbnNlY3JldA==
  mongo-host: bW9uZ28taGVhZGxlc3M=